### ISSUE TITLE
Lack of CSS

### ISSUE THREAD

**Issue by joker314** [chooper100/ftpconnect#1]
I reccomend deciding on a theme colour if you haven't already, picking a good font, aligning text, and more! I might drop a PR later :)

**Comment by ed-cooper** [comment]
Haha yes, it is a bit bland at the moment 😉

There's a lot of code I already have on my computer for an old project I'm basing this on, so hopefully I can borrow some of that 😄

**Comment by ed-cooper** [comment]
Screenshots of previous version:

Login page:

![login](https://cloud.githubusercontent.com/assets/14095134/20038082/398bbf9c-a425-11e6-92f1-6ab4401cd5bf.png)

IDE:

![ide](https://cloud.githubusercontent.com/assets/14095134/20038083/40bd7a3a-a425-11e6-85d4-b8abca762d1c.png)

**Comment by joker314** [comment]
Oh, yours is way better: http://output.jsbin.com/yolocubaji

Your version looks sooo coool! :)

**Comment by ed-cooper** [comment]
Yep, we're using material design as the inspiration:
https://material.google.com/

**Comment by CosmicWebServices** [comment]
NICE!!!!!!!! whoa caps lock

**Comment by joker314** [comment]
I am soo bored -- do you need any code written?

###### I'd love to help

**Comment by CosmicWebServices** [comment]
lol

**Comment by ed-cooper** [comment]
It's great that you want to help, but I just want to get a decent project structure in place before I get a load of code submissions from everyone 😄

**Comment by ed-cooper** [comment]
Ok, after several commits I'm now fairly satisfied with the design of the home page (although it is far from complete)

Closing this now, future improvements can be added as separate issues
