### ISSUE TITLE
Will nodejs be better for this type of project?

### ISSUE THREAD

**Issue by CosmicWebServices** [chooper100/ftpconnect#4]
- @IcyCoder on scratch

**Comment by ed-cooper** [comment]
The web hosting I am currently using only has support for PHP, so NodeJS isn't an option, so theoretically I could close this now.

However, I am curious for future projects, so why would you recommend NodeJS over PHP? I only have limited experience in NodeJS so I'd be interested in your reasoning

**Comment by CosmicWebServices** [comment]
Nodejs has faster development time and lots of easy to install modules that may help.

**Comment by ed-cooper** [comment]
Ok, I'll bear that in mind in future
